const assert=require('node:assert/strict');
const {tplus,sampleAt,bounds,phase,card}=require('../app/static/timeline.js');
assert.equal(tplus(245),'T+04:05');
assert.equal(tplus(0),'T+00:00');
assert.equal(tplus(3600),'T+60:00');
assert.equal(tplus(-61),'T−01:01');
const a={t_s:120,elevation:0,azimuth:359,range_km:600,sun_altitude:-25,altitude_km:100,powered:true,plume:true,sunlit:false};
const b={...a,t_s:180,elevation:20,azimuth:1,range_km:300,powered:false};
let p=sampleAt([a,b],150,5);
assert.equal(p.azimuth,0,'Azimuth interpolation must cross north, not south');
assert.equal(p.elevation,10);assert.equal(p.ordinary,true);assert.equal(p.range_km,450);
assert.equal(sampleAt([a,b],119),null,'Do not invent earlier booster telemetry');
assert.equal(sampleAt([a,b],181),null);
assert.equal(sampleAt([a,{...b,t_s:400}],250),null,'Do not connect discontinuous stages');
assert.equal(sampleAt([a,b],180).powered,false,'Power transitions apply at the actual event');
const d=bounds([a,b],[{start_s:140,end_s:170}],false,5);
assert.equal(d.x0,0);assert.equal(d.x1,180);assert(d.y1<90,'Fit low trajectories instead of flattening them');
const z=bounds([{...a,t_s:0},{...b,t_s:600}],[{start_s:300,end_s:400}],true,5);
assert.equal(z.x0,270);assert.equal(z.x1,430);
assert.match(phase(null,5),/No trajectory/);
assert.match(phase({...a,above:false,elevation:3},5),/5°/);
assert.match(phase({...p,jellyfish:true},5),/Sunlit/);
const empty=card({prediction:{viewing_plan:{status:'no_path',first:null}}});
assert(!empty.includes('T+00:00'));
console.log('Timeline time-axis, interpolation, state and no-data assertions passed.');
